### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by ulisigi** [adsajeni/prj-rev-bwfs-dasmoto#2]
While your project closely resembles the design specification, there are styling deviations in 2-3 sections. Although not explicitly specified in the redline document, all text in this project should have a `font-family` of `Helvetica`.

If we compare the font of the design specification:
![image](https://user-images.githubusercontent.com/26392454/52318029-8da5e600-2990-11e9-9ceb-12b1cb485af9.png)
with the default browser styling:
![image](https://user-images.githubusercontent.com/26392454/52318045-9a2a3e80-2990-11e9-8305-994c8b681c36.png)
we see that the design specification utilizes a sans-serif font, while the default is a serif font.

**Comment by adsajeni** [comment]
I'll try to keep that in mind going forward.
